### ISSUE TITLE
Find model collection using model urlRoot property

### ISSUE THREAD

**Issue by Seebiscuit** [Conductor/backbone.hoard#47]
It's a common use-case for a model that belongs to a collection to be populated outside of that collection. It's reasonable that if the model was modified on the back end, all collections where that model exists should be updated. 

On executing a strategy on a cached model if that model does not contain a reference to a hoard collection the model request is not updated on any collection, even if the parent collection is managed by hoard.

However, we can take advantage of a model's `urlRoot` property. If a collection matching the `urlRoot` of the model is found we can assume that the model belongs to the same collection.

**Comment by cmaher** [comment]
:+1:

**Comment by cmaher** [comment]
After a lot of discussion on the gitter, we came to the following conclusions:

* this would cause consistency problems across page reloads
* this is outside the scope of hoard, which aims to only interact with anything via sync
* this can be handled via
```js
// the model
var model = new HoardAwareModel();
model.save();

//some time later
var collection = new HoardAwareCollection();
var control = model.sync.hoardControl;
control.store.invalidate(control.policy.getKey(model));
collection.add(model);
collection.save();
```
